# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookstore.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookstore.proto\x12\tbookstore\"9\n\nBookSearch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\"3\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x32>\n\tBookStore\x12\x31\n\x05\x46irst\x12\x15.bookstore.BookSearch\x1a\x0f.bookstore.Book\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKSEARCH']._serialized_start=30
  _globals['_BOOKSEARCH']._serialized_end=87
  _globals['_BOOK']._serialized_start=89
  _globals['_BOOK']._serialized_end=140
  _globals['_BOOKSTORE']._serialized_start=142
  _globals['_BOOKSTORE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
